### ISSUE TITLE
Support Elasticsearch 6

### ISSUE THREAD

**Issue by mattiassluis** [kpn-digital/py-timeexecution#34]
Currently the requirements/requirements-base.txt specifies elasticsearch==5 which results in installing the 5.0.0 client instead it should allow ranges and including support for elasticsearch 6.

**Comment by igbun** [comment]
Support for elasticsearch 6 was added in version 3.3.0: https://github.com/kpn-digital/py-timeexecution/releases/tag/3.3.0
